In [1]:
import pandas as pd
import numpy as np
import math
from tqdm import tqdm

## Open file
fp = open('doc_list.txt','r')
doc_list = [ ]
line = fp.readline()

## 用 while 逐行讀取檔案內容，直至檔案結尾
while line:
    line = line.replace('\n','')
    doc_list.append(line)
    line = fp.readline()
 
fp.close()
print(len(doc_list))

## Open file
fp = open('query_list.txt','r')
query_list = [ ]
line = fp.readline()

## 用 while 逐行讀取檔案內容，直至檔案結尾
while line:
    line = line.replace('\n','')
    query_list.append(line)
    line = fp.readline()
 
fp.close()
print(len(query_list))

voc = [ ]

2265
800


In [2]:
# Open file
doc_len = 0
doc_temp = [ ]
doc = [ ]

while doc_len < len(doc_list) :
    fp = open('Document/'+doc_list[doc_len],'r')
    i = 0
    while i < 3:
        buffer = fp.readline()
        i += 1
    
    doc_temp = fp.read()
    doc_temp = doc_temp.replace('-1','')
    doc_temp = doc_temp.split()
    doc = doc + doc_temp
    doc = list(set(doc))

    fp.close()
    doc_len += 1
    
print(len(doc))

13290


In [3]:
# Open file
query_len = 0
query_temp = [ ]
query = [ ]

while query_len < len(query_list) :
    fp = open('Query/'+query_list[query_len],'r')
    
    query_temp = fp.read()
    query_temp = query_temp.replace('-1','')
    query_temp = query_temp.split()
    query = query + query_temp
    #word = word + query_temp
    query = list(set(query))
    
    fp.close()
    query_len += 1
    
print(len(query))

9735


In [4]:
voc = doc + query
voc = list(set(voc))
print(len(voc))

15884


In [5]:
tfd = np.zeros( (len(voc), doc_len), dtype=np.int )
#print(tfd)
tfq = np.zeros( (len(voc), query_len), dtype=np.int )
#print(tfq)

In [6]:
x = 0
temp = [ ]

while x < doc_len :
    fp = open('Document/'+doc_list[x],'r')
    
    i = 0
    while i < 3:
        buffer = fp.readline()
        i += 1
    
    temp = fp.read()
    temp = temp.replace('-1','')
    temp = temp.split()

    y = 0
    for w in voc :
        for dc in temp :
            if w == dc :
                tfd[y][x] += 1
        y += 1
        
    fp.close()
    x += 1
    
print(tfd)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
#print(np.unique(tfd, axis=0))

In [8]:
x = 0
while x < query_len :
    fp = open('Query/'+query_list[x],'r')
    
    i = 0
    while i < 3:
        buffer = fp.readline()
        i += 1
    
    temp = fp.read()
    temp = temp.replace('-1','')
    temp = temp.split()

    y = 0
    for w in voc :
        for q in temp :
            if w == q :
                tfq[y][x] += 1
        y += 1
        
    fp.close()
    x += 1
    
print(tfq)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
#print(np.unique(tfq, axis=0))
for i in range(len(voc)) :
    for j in range(doc_len) :
        if tfd[i][j] > 0 :
            tfd[i][j] = math.log(tfd[i][j],2) + 1
            
for i in range(len(voc)) :
    for j in range(query_len) :
        if tfq[i][j] > 0 :
            tfq[i][j] = math.log(tfq[i][j],2) + 1

In [10]:
idf = np.zeros( (len(voc), 1 ), dtype=np.float )
#print(idf)

for i in range(len(voc)) :
    for j in range(doc_len) :
        if tfd[i][j] > 0 :
            idf[i][0] += 1

print(idf.shape)
#print(np.unique(idf))

for i in range(len(voc)) :
    if idf[i][0] != 0 :
        idf[i][0] = doc_len / idf[i][0]
        idf[i][0] = math.log(idf[i][0],10) 
        
print(idf)

(15884, 1)
[[2.87794695]
 [0.        ]
 [2.87794695]
 ...
 [3.35506821]
 [3.35506821]
 [2.75300822]]


In [11]:
tfidfd = [ ]
tfidfd = np.zeros( (len(voc), doc_len), dtype=np.float )
print(tfidfd.shape)

tfidfq = [ ]
tfidfq = np.zeros( (len(voc), query_len), dtype=np.float )
print(tfidfq.shape)


(15884, 2265)
(15884, 800)


In [12]:
for i in range(len(voc)) :
    for j in range(doc_len) :
        tfidfd[i][j] = tfd[i][j] * idf[i][0]
print(np.unique(tfidfd))        

for i in range(len(voc)) :
    for j in range(query_len) :
        tfidfq[i][j] = tfq[i][j] * idf[i][0]
print(np.unique(tfidfq))

[0.00000000e+00 9.59767201e-04 1.91953440e-03 ... 1.52701911e+01
 1.67753410e+01 1.72676817e+01]
[0.00000000e+00 9.59767201e-04 1.91953440e-03 ... 1.52701911e+01
 1.67753410e+01 1.83242293e+01]


In [13]:
from sklearn.metrics.pairwise import cosine_similarity

vsm_1 = [ ]
vsm_1 = np.zeros( (query_len, doc_len), dtype=np.float )
print(vsm_1.shape)

(800, 2265)


In [14]:
#vsm_1 = cosine_similarity(tfidfd.T, tfidfq.T)

for i in range(query_len) :
    for j in range(doc_len) :
        vsm_1[i][j] = cosine_similarity([tfidfd[:,j]], [tfidfq[:,i]])

#vsm_1 = vsm_1.T
print(vsm_1.shape)

(800, 2265)


In [15]:
ranking = pd.DataFrame(vsm_1, index = query_list, columns = doc_list)
#print(ranking)


In [16]:
ranking = ranking.sort_values(by = query_list[0],ascending= False, axis=1)
ranking

VOM19980630.0730.0191  VOM19980630.0700.0238  \
40001.query               0.210643               0.210643   
40002.query               0.006827               0.006827   
40003.query               0.021220               0.021220   
40004.query               0.036927               0.036927   
40005.query               0.001957               0.001957   
40006.query               0.182941               0.182941   
40007.query               0.154912               0.154912   
40008.query               0.020147               0.020147   
40009.query               0.021911               0.021911   
40010.query               0.019696               0.019696   
40011.query               0.003022               0.003022   
40012.query               0.043113               0.043113   
40013.query               0.006889               0.006889   
40014.query               0.004951               0.004951   
40015.query               0.189429               0.189429   
40016.query               0.004277               0.004277   
40017.query               0.034226               0.034226   
40018.query               0.001631               0.001631   
40019.query               0.018008               0.018008   
40020.query               0.008308               0.008308   
40021.query               0.022434               0.022434   
40022.query               0.005162               0.005162   
40023.query               0.003484               0.003484   
40024.query               0.007085               0.007085   
40025.query               0.030082               0.030082   
40026.query               0.005985               0.005985   
40027.query               0.005474               0.005474   
40028.query               0.005456               0.005456   
40029.query               0.018392               0.018392   
40030.query               0.000059               0.000059   
...                            ...                    ...   
40771.query               0.017478               0.017478   
40772.query               0.034008               0.034008   
40773.query               0.020978               0.020978   
40774.query               0.023174               0.023174   
40775.query               0.013755               0.013755   
40776.query               0.020597               0.020597   
40777.query               0.022727               0.022727   
40778.query               0.031052               0.031052   
40779.query               0.001139               0.001139   
40780.query               0.060010               0.060010   
40781.query               0.004155               0.004155   
40782.query               0.004290               0.004290   
40783.query               0.010188               0.010188   
40784.query               0.019478               0.019478   
40785.query               0.011128               0.011128   
40786.query               0.010785               0.010785   
40787.query               0.058678               0.058678   
40788.query               0.069315               0.069315   
40789.query               0.008186               0.008186   
40790.query               0.009081               0.009081   
40791.query               0.005311               0.005311   
40792.query               0.016467               0.016467   
40793.query               0.019994               0.019994   
40794.query               0.014859               0.014859   
40795.query               0.062532               0.062532   
40796.query               0.006684               0.006684   
40797.query               0.004825               0.004825   
40798.query               0.013997               0.013997   
40799.query               0.044886               0.044886   
40800.query               0.075948               0.075948   

             VOM19980630.0900.0105  VOM19980604.0700.0157  \
40001.query               0.210143               0.167003   
40002.query               0.006811               0.028443   
40003.query               0.021170             

In [25]:
Rq = 5

alpha = 0.3
alpha_idf = np.zeros( (len(voc), 1 ), dtype=np.float )

beta = 1.1
beta_idf = np.zeros( (len(voc), 1 ), dtype=np.float )

new_idf = np.zeros( (len(voc), 1 ), dtype=np.float )

tfidfq_2 = np.zeros( (len(voc), query_len), dtype=np.float )
print(tfidfq_2.shape)

for n in range(query_len) :
    ranking = ranking.sort_values(by = query_list[n],ascending= False, axis=1)
    name = ranking.columns
    name = np.asarray(name)

    #抓出原本的tfidf_doc

    for i in range(Rq) :
        for j in range(doc_len) :
            if name[i] == doc_list[j]:
                #print(name[i], j)
                beta_idf = beta_idf[:,[0]] + tfidfd[:,[j]]
            
    alpha_idf = alpha_idf[:,[0]] + tfidfq[:,[n]]
    alpha_idf = alpha_idf * alpha
    
    beta_idf = beta_idf * beta * (1/Rq)

    new_idf = alpha_idf + beta_idf
    #print(alpha_idf, beta_idf, new_idf)

    tfidfq_2[:,[n]] = new_idf
    #print(tfidfq_2[:,[n]])

(15884, 800)


In [26]:
print(tfidfq_2)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 2.36665238e-042
  5.20663524e-043 1.14545975e-043]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 4.87803126e-110
  1.46340938e-110 4.39022813e-111]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]


In [27]:
print(tfidfd.shape)
print(tfidfq_2.shape)
vsm_2 = [ ]
vsm_2 = np.zeros( (query_len, doc_len), dtype=np.float )
print(vsm_2.shape)

(15884, 2265)
(15884, 800)
(800, 2265)


In [28]:
#vsm_2 = cosine_similarity(tfidfd.T, tfidfq_2.T)
#print(vsm_2[0][0])
for i in range(query_len) :
    for j in range(doc_len) :
        vsm_2[i][j] = cosine_similarity([tfidfd[:,j]], [tfidfq_2[:,i]])
#         print(vsm_2[i][j])
#         input()

#vsm_2 = vsm_2.T
print(vsm_2)
print(vsm_2.shape)

[[0.01605429 0.01632827 0.01816669 ... 0.01289178 0.01339649 0.00661442]
 [0.09834463 0.05363987 0.0516624  ... 0.050806   0.03905569 0.03431305]
 [0.06635962 0.03883987 0.04346299 ... 0.04595465 0.03957829 0.03209139]
 ...
 [0.02923153 0.04555753 0.04242503 ... 0.02615071 0.02140626 0.0293437 ]
 [0.06107942 0.06110583 0.04535251 ... 0.04822187 0.04778577 0.04658813]
 [0.04996628 0.04834675 0.04959038 ... 0.05785977 0.05114251 0.06200297]]
(800, 2265)


In [29]:
ranking = pd.DataFrame(vsm_2, index = query_list, columns = doc_list)
#print(ranking)


In [30]:
f = open('M10715086.txt','w') 
f.write("Query,RetrievedDocuments\n")
f.close()

f = open('M10715086.txt','a') 

for i in range(query_len) :
    f.write(query_list[i] + ',')
    ranking = ranking.sort_values(by = query_list[i],ascending= False, axis=1)
    name = ranking.columns
    name = np.asarray(name)
    for j in range(doc_len):
        f.write(name[j] + ' ')
    f.write('\n')

f.close()